global:
  scrape_interval: 60s
  scrape_timeout: 60s
  evaluation_interval: 1m
  external_labels:
    monitor: monitor
scrape_configs:
- job_name: node
  static_configs:
  - targets: ['172.31.41.141:9100','172.31.42.226:9100','172.31.41.148:9100','172.31.41.231:9100','172.31.33.143:9100','172.31.41.53:9100','172.31.42.9:9100','172.31.42.179:9100']
       # - targets: ["172.31.41.141:9100","172.31.42.226:9100","172.31.41.148:9100","172.31.41.231:9100","172.31.33.143:9100","172.31.41.53:9100","172.31.42.9:9100","172.31.42.179:9100"]
- job_name: elasticsearch_metric
  static_configs:
  - targets: ['172.31.41.141:9114','172.31.42.226:9114','172.31.41.148:9114','172.31.41.231:9114','172.31.33.143:9114','172.31.41.53:9114','172.31.42.9:9114','172.31.42.179:9114']
- job_name: ecs_node_exporter_discovery
  honor_timestamps: true
  scrape_interval: 60s
  scrape_timeout: 60s
  metrics_path: /metrics
  scheme: http
  ec2_sd_configs:
  - endpoint: ""
    region: ap-southeast-1
    profile: arn:aws:iam::616035352558:instance-profile/alpha-ecs-hosts
    refresh_interval: 1m
    port: 9100
    filters:
    - name: tag:aws:autoscaling:groupName
      values:
      - preprod-v2-ecs-hosts
- job_name: preprod-eks
  honor_timestamps: true
  scrape_interval: 60s
  scrape_timeout: 60s
  metrics_path: /metrics
  scheme: http
  ec2_sd_configs:
  - endpoint: ""
    region: ap-southeast-1
    profile: arn:aws:iam::616035352558:instance-profile/eks-98c30a8e-58aa-ac04-fdad-311d3643f548
    refresh_interval: 1m
    port: 9100
    filters:
    - name: tag:eks:cluster-name
      values:
      - preprod-eks-cluster
- job_name: preprod-v2-prometheus-cadvisor
  honor_timestamps: true
  scrape_interval: 60s
  scrape_timeout: 60s
  metrics_path: /metrics
  scheme: http
  ec2_sd_configs:
  - endpoint: ""
    region: ap-southeast-1
    profile: arn:aws:iam::616035352558:instance-profile/alpha-ecs-hosts
    refresh_interval: 1m
    port: 9200
    filters:
    - name: tag:aws:autoscaling:groupName
      values:
      - preprod-v2-ecs-hosts
- job_name: app
  honor_timestamps: true
  scrape_interval: 60s
  scrape_timeout: 60s
  metrics_path: /monitoringLogs
  scheme: http
  file_sd_configs:
  - files:
    - /mnt/efs/data/ecs_file_sd.yml
    refresh_interval: 1m
